// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BBreadcrumb: typeof import('bootstrap-vue')['BBreadcrumb']
    BButton: typeof import('bootstrap-vue')['BButton']
    BButtonGroup: typeof import('bootstrap-vue')['BButtonGroup']
    BButtonToolbar: typeof import('bootstrap-vue')['BButtonToolbar']
    BCol: typeof import('bootstrap-vue')['BCol']
    BCollapse: typeof import('bootstrap-vue')['BCollapse']
    BContainer: typeof import('bootstrap-vue')['BContainer']
    BDropdownItem: typeof import('bootstrap-vue')['BDropdownItem']
    BFormCheckbox: typeof import('bootstrap-vue')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue')['BFormSelect']
    BImgLazy: typeof import('bootstrap-vue')['BImgLazy']
    BInputGroup: typeof import('bootstrap-vue')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue')['BInputGroupAppend']
    BInputGroupPrepend: typeof import('bootstrap-vue')['BInputGroupPrepend']
    BInputGroupText: typeof import('bootstrap-vue')['BInputGroupText']
    BModal: typeof import('bootstrap-vue')['BModal']
    BNavbar: typeof import('bootstrap-vue')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue')['BNavForm']
    BNavItemDropdown: typeof import('bootstrap-vue')['BNavItemDropdown']
    BPagination: typeof import('bootstrap-vue')['BPagination']
    BRow: typeof import('bootstrap-vue')['BRow']
    BSkeletonWrapper: typeof import('bootstrap-vue')['BSkeletonWrapper']
    BSpinner: typeof import('bootstrap-vue')['BSpinner']
    BTable: typeof import('bootstrap-vue')['BTable']
  }
}
